name: Hello CI
on: [push]
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: echo "Hello CI/CD"
      - run: echo "Branche $GITHUB_REF_NAME et Auteur $GITHUB_ACTOR"
